### ISSUE TITLE
Update extract_linux_0.1.sh 

### ISSUE THREAD

**Issue by elc0rr3Km1n0s** [maximeolivier/pyCAF#1]
Hello,

I propose you the following patch to fix failed importation of /etc/os-release in Debian 8 by adding "--reference" option to the archive command.

-tar cjf $OUTDIR/etc.tar.bz2 -p --atime-preserve /etc
+tar cjf $OUTDIR/etc.tar.bz2 -p --atime-preserve --dereference /etc

Thanks

**Comment by maximeolivier** [comment]
Done.

Thanks for your contribution and sorry for the delay ;)
